--Executive KPIs


--Q1 What is the Total Revenue Generated by the Business?
SELECT
    ROUND(SUM(price::NUMERIC), 2) AS total_revenue
FROM order_items;


--Q2 What is the Total Number of Orders?
SELECT
    COUNT(order_id) AS total_orders
FROM orders;


--Q3 What is the Total Number of Customers?
SELECT
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM customers;


--Q4 What is the Average Order Value (AOV)?
SELECT
    ROUND(AVG(price::NUMERIC), 2) AS average_order_value
FROM order_items;


--Q5 What is the Average Customer Review Score?
SELECT
    ROUND(AVG(review_score::NUMERIC), 2) AS average_review_score
FROM order_reviews;